# Generated by Django 3.2.5 on 2021-08-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
